// <auto-generated />
namespace LTQL_17210500100.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sanphamr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sanphamr));
        
        string IMigrationMetadata.Id
        {
            get { return "202206280238069_sanphamr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
