// <auto-generated />
namespace LTQL_17210500100.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sanpham1r : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sanpham1r));
        
        string IMigrationMetadata.Id
        {
            get { return "202206280239226_sanpham1r"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
