// <auto-generated />
namespace NQLBaiTapLon010.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class chucvu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chucvu));
        
        string IMigrationMetadata.Id
        {
            get { return "202203140410516_chucvu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
